import { useMigrations } from 'drizzle-orm/expo-sqlite/migrator';
import { Tabs } from 'expo-router';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';
import { GestureHandlerRootView } from 'react-native-gesture-handler';

import { db } from '@/db/client';
import migrations from '../../drizzle/migrations';

/**
 * Root layout. Applies the on-device schema via versioned migrations before
 * any screen renders, then shows a Notes | Tasks tab bar (F7). Migrations
 * are generated by drizzle-kit (see drizzle/ and drizzle.config.ts) — never
 * created ad-hoc at startup. Wrapped in GestureHandlerRootView so Tasks'
 * swipe-to-delete (react-native-gesture-handler's Swipeable) receives touch
 * events — nothing in the app wrapped this before F7.
 */
export default function RootLayout() {
  const { success, error } = useMigrations(db, migrations);

  if (error) {
    return (
      <View style={styles.center}>
        <Text style={styles.errorTitle}>Database migration failed</Text>
        <Text style={styles.errorDetail}>{error.message}</Text>
      </View>
    );
  }

  if (!success) {
    return (
      <View style={styles.center}>
        <ActivityIndicator />
      </View>
    );
  }

  return (
    <GestureHandlerRootView style={styles.flex}>
      <Tabs>
        <Tabs.Screen name="index" options={{ title: 'Notes' }} />
        <Tabs.Screen name="tasks" options={{ title: 'Tasks' }} />
      </Tabs>
    </GestureHandlerRootView>
  );
}

const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    gap: 8,
  },
  errorTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#b00020',
  },
  errorDetail: {
    fontSize: 13,
    color: '#666',
    textAlign: 'center',
  },
});
